### ISSUE TITLE
dead link

### ISSUE THREAD

**Issue by KooShnoo** [cyndifusic/kaizo-tanks#2]
https://github.com/cyndifusic/kaizo-tanks/blob/9ec88119fa2b8dd3e77cb254b184836358e084e5/index.html#L38C64-L38C153

this link for [Blitzkrieg Tools](http://jimmysstuff.tk/index/blitzkriegtoolsr1/0-18) is broken. `.tk` domains are no longer free.

**Comment by cyndifusic** [comment]
fixed
